### ISSUE TITLE
Navi 21 rendering glitches, macOS Sequoia

### ISSUE THREAD

**Issue by larini** [ChefKissInc/NootRX#95] opened 2024-11-14 19:26 UTC
### macOS Version

Sequoia

### What is your CPU's model?

Ryzen 3700X

### What is your GPU's model?

RX 6950 XT

### Please describe the behaviour in detail.

My GPU is a XFX RX 6950 XT Merc 319.
Works perfect with Sonoma, but after upgrade to Sequoia, the machine is very slow, and full of strange artifacts on screen.
This is a bug of this model or Sequoia breaking change?

![IMG_4650](https://github.com/user-attachments/assets/a39f36ff-dd57-4206-abe1-d0ccbb277acb)
![IMG_4651](https://github.com/user-attachments/assets/4e10e90d-2881-4001-a3e5-09880694690f)
![IMG_4654](https://github.com/user-attachments/assets/aa5eb109-d914-4d53-b587-5d06a534ee7d)

### What should've happened instead?

Works like Sonoma.

**Comment by larini** [comment] 2024-11-20 07:47
Yes, version 15.1

**Comment by VisualEhrmanntraut** [comment] 2024-11-20 15:59
Uh well I told some people with Navi 22 to test and they don't have any issues. So I'm not sure what I broke with Navi 21. I'll have to take a look at a later point.

**Comment by shrisha108** [comment] 2024-11-21 07:08
I think he have to try other method, spoofing, etc and see. If his card is fried he would noticed it in Windows, right?
I decide to try NootRX after I'm getting sometimes kernel panics caused by bluetoothd. Someone was mentioned on Reddit that weirdly enough somehow it is related to GPU. So I hope your kext will fix it. Fingers crossed. Thank you so much for your work by the way.

**Comment by shrisha108** [comment] 2024-11-21 08:24
New finding... METAL performance in Geekbench degraded considerably. Checked twice rebooted with spoofed in OC config and with NootRX.kext. Don't know if it is only in Geekbench, where else should I check?
<img width="1117" alt="Screenshot 2024-11-21 at 12 57 43" src="https://github.com/user-attachments/assets/490c801e-1b54-46cc-8f1f-85aef206ec10">

**Comment by shrisha108** [comment] 2024-11-23 03:06
Should I open new issue?

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 03:08
No, I am not the developer of macOS therefore Apple bugs are not my responsibility.

**Comment by shrisha108** [comment] 2024-11-23 03:11
Ok, got it. Seems to me it's related to NootRX.kext. I rebooted with spoofed OC config again agter and results was back to high as it was. So I thought it's related...

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 03:14
No, it's not a bug with the kext. The kext uses the existing drivers just as WhateverGreen does, with the exception of firmware and setting updates extracted from the Windows drivers. If performance regressions are introduced by these changes, it's AMD's fault.

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 03:16
Also, I do have a firmware update pending, but none of the internal quality control testers have tested it yet.

**Comment by shrisha108** [comment] 2024-11-23 03:18
That's nice, will wait for updated kext then . Or I can test it for if it's compiled.

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 03:20
Sure, here's a build.
[NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17878238/NootRX-1.0.0-RESEARCH_RELEASE.zip)

**Comment by shrisha108** [comment] 2024-11-23 03:21
Great! Will report in a half an hour.

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 03:54
@shrisha108 Could you also try this?
[NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17878383/NootRX-1.0.0-RESEARCH_RELEASE.zip)

**Comment by shrisha108** [comment] 2024-11-23 03:54
Oh, thank you. So my whitelisting of MMIO is not proper probably?

**Comment by shrisha108** [comment] 2024-11-23 03:54
> @shrisha108 Could you also try this? [NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17878383/NootRX-1.0.0-RESEARCH_RELEASE.zip)

sure

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 03:55
> Oh, thank you. So my whitelisting of MMIO is not proper probably?

Can't say for sure, it could also be one of the kexts being written bad.

**Comment by shrisha108** [comment] 2024-11-23 03:58
> @shrisha108 Could you also try this? [NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17878383/NootRX-1.0.0-RESEARCH_RELEASE.zip)

You sure it's another one? Size is fully identical with the one you gave me half an hour ago

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 04:00
Good catch, I guess I forgot to recompile.
[NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17878403/NootRX-1.0.0-RESEARCH_RELEASE.zip)

**Comment by shrisha108** [comment] 2024-11-23 04:02
> Good catch, I guess I forgot to recompile. [NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17878403/NootRX-1.0.0-RESEARCH_RELEASE.zip)

Sorry but this one is too :) 
<img width="551" alt="Screenshot 2024-11-23 at 09 32 31" src="https://github.com/user-attachments/assets/becaf759-8ddf-47f2-a8e0-38f8c9bdef26">

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 04:06
I'm 100% sure it's a fresh build. It might just be a coincidence that the size is identical.

**Comment by shrisha108** [comment] 2024-11-23 04:07
> I'm 100% sure it's a fresh build. It might just be a coincidence that the size is identical.

Ok, sure.

**Comment by shrisha108** [comment] 2024-11-23 04:36
Yes, that's definitely latest build. I've got hard hang, even reset button didn't work, Have to fully switched off power supply.
Here is a result:

[new_panic.txt](https://github.com/user-attachments/files/17878473/new_panic.txt)

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 04:37
"NootRX: @ Failed to find a compatible GPU" How would that be possible? I only changed one line to enable the SMC firmware injection for Navi 21

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 04:38
<img width="827" alt="image" src="https://github.com/user-attachments/assets/6f844e6c-d035-4ddc-b1da-9e7059a47189">
This is all I did

**Comment by shrisha108** [comment] 2024-11-23 04:42
Nope, device properties is empty and whatevergreen is disabled
<img width="1503" alt="Screenshot 2024-11-23 at 10 12 39" src="https://github.com/user-attachments/assets/75794f54-dd0c-4d76-b542-f1fbc7c9800a">

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 04:44
Use of configurator software is frowned upon. Ignoring further inquiries.

**Comment by shrisha108** [comment] 2024-11-23 04:45
No, I just open it up for visual confirmation

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 04:45
It edits it regardless of if you make any edits using the software.

**Comment by shrisha108** [comment] 2024-11-23 04:49
I know that and using a plist editor for OC config editing.

**Comment by larini** [comment] 2024-11-23 08:53
Hi, there something that I can do to help you?

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 08:54
@larini Yeah, test that last build I sent

**Comment by larini** [comment] 2024-11-23 10:37
@VisualEhrmanntraut , doesn't work. Same behavior. Slow down all system, artifacts, locks... 
My GPU is working perfect in Windows and Sonoma.
My I can help with something else?

**Comment by shrisha108** [comment] 2024-11-23 13:25
> It gets edited automatically as soon as it's opened.
FYI after closing OCAT I checked my config file hasn't changed, creation time was the same as I edited in ProperTree half an hour before, so no need to be that paranoid. If you still interested  I tried again with last asked by you kext and here is panic log:
[next panic.txt](https://github.com/user-attachments/files/17879830/next.panic.txt)

RX 6800 card mentioned in there. May be that's why performance regression is happen?

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 13:28
Thanks for the correct panic log. I'll send a new build later.

**Comment by VisualEhrmanntraut** [comment] 2024-11-23 21:22
@shrisha108 @larini 
[NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17882593/NootRX-1.0.0-RESEARCH_RELEASE.zip)

**Comment by shrisha108** [comment] 2024-11-24 04:27
> @shrisha108 @larini [NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17882593/NootRX-1.0.0-RESEARCH_RELEASE.zip)

Ok, tried to boot two times, didn't get to panic just stuck in a beginning of booting. Booted in verbose mode to see where it stoped. If it give any info I'm attaching pics of two boots.

![IMG_20241124_093248](https://github.com/user-attachments/assets/5627cb7c-053c-462a-aad7-3749a35c8e36)

![IMG_20241124_093638](https://github.com/user-attachments/assets/96a52a46-cf3f-4ed8-9700-e7f8d986ede2)

Should I try to boot with debug OC version? Is there would be any use if you look at my spoofed entry for my card? Or can I save firmware of my card for nootrx.kext if it will help?

**Comment by VisualEhrmanntraut** [comment] 2024-11-24 04:31
?

**Comment by shrisha108** [comment] 2024-11-24 04:59
> Oh, the patches are wrong. Try this @shrisha108 [NootRX-1.0.0-RESEARCH_RELEASE.zip](https://github.com/user-attachments/files/17891795/NootRX-1.0.0-RESEARCH_RELEASE.zip)

Successful boot with this one. METAL score still low.

**Comment by VisualEhrmanntraut** [comment] 2024-11-24 05:00
Was trying to fix a different bug, the SMC firmware injection was disabled for Navi 21 due to that panic, but now it's fixed, thanks for the testing.

**Comment by shrisha108** [comment] 2024-11-24 05:02
Happy to help. You still thinks that performance regression is not related to kext?

**Comment by VisualEhrmanntraut** [comment] 2024-11-24 05:02
My bets are still on #69

**Comment by shrisha108** [comment] 2024-11-24 05:12
Is there any way I can help with firmwares?

**Comment by VisualEhrmanntraut** [comment] 2024-11-24 05:13
As an end-user, not really.

**Comment by shrisha108** [comment] 2024-11-24 05:15
Got it, so will wait then until #69 will be resolved. Thank you.

**Comment by VisualEhrmanntraut** [comment] 2024-11-26 18:28
@larini @shrisha108 try the build of the latest commit

**Comment by alvindimas05** [comment] 2024-11-27 11:01
The new NootRX gives a better performance in my RX 6600. Around 33% increase of performance.
WhateverGreen (80320)
https://browser.geekbench.com/v6/compute/2712419
Old NootRX (76268)
https://browser.geekbench.com/v6/compute/2712447
New NootRX (107523)
https://browser.geekbench.com/v6/compute/3216761

**Comment by 28862886** [comment] 2024-11-29 08:20
hi, the newest NootRX got very slow and hang after wake from sleep if play video, anyone had same issue?
i had test all the builds and issue look like from here --> https://github.com/ChefKissInc/NootRX/actions/runs/11993434769
Older builds are working fine.

**Comment by VisualEhrmanntraut** [comment] 2024-11-29 08:38
You haven't even specified which GPU and which CPU.

**Comment by 28862886** [comment] 2024-11-29 17:04
hi, sorry my bad,
i got x299 intel i9-9980xe with Sapphire RX 6950
and the cpu needed TSCSync to work, i think it conflict with new nootrx,
thank you for your help.

**Comment by VisualEhrmanntraut** [comment] 2024-11-29 17:34
When did you try it? I made an update 2 days ago

**Comment by VisualEhrmanntraut** [comment] 2024-11-29 17:52
> sorry waste your time,,

I'm just trying to make sure it works properly, don't worry.

**Comment by 28862886** [comment] 2024-11-29 18:27
your best creator ever,
can you help me create build use this --> https://github.com/ChefKissInc/NootRX/actions/runs/11941828922
and change "PP_WorkLoadPolicyMask=16" or "PP_WorkLoadPolicyMask=0x10" ,
it make gpu get better performance and skip hang panic for me, can you help please?

**Comment by VisualEhrmanntraut** [comment] 2024-11-29 18:27
16 is 0x10

**Comment by VisualEhrmanntraut** [comment] 2024-11-29 18:28
the field takes in hexadecimal, you basically gave it an invalid policy and it fell back to default

**Comment by larini** [comment] 2024-11-29 21:11
> [@larini](https://github.com/larini) [@shrisha108](https://github.com/shrisha108) try the build of the latest commit

Not work here at all..

![Image](https://github.com/user-attachments/assets/e8096581-5d1b-4811-881a-e65b662815db)

**Comment by VisualEhrmanntraut** [comment] 2024-11-30 03:49
Well, you can't be the only one with the rendering glitches. Besides, this GPU is natively supported, NootRX is really just injecting some personalities and updated firmware, which are taken from Windows.

**Comment by larini** [comment] 2024-11-30 20:24
Sorry @VisualEhrmanntraut , I don't know what's happen. Sonoma works like a charm... Thanks

**Comment by VisualEhrmanntraut** [comment] 2024-11-30 20:26
The issue could be fixed but the shaders be cached and showing corruption still

**Comment by larini** [comment] 2024-12-01 09:28
A strange behavior is that the system becomes slow, broken, sometimes it works and after a while it crashes, then it comes back...
Maybe I'll have to die with Sonoma after all.

**Comment by VisualEhrmanntraut** [comment] 2024-12-01 13:04
@larini Maybe running these will help
```sh
find $(getconf DARWIN_USER_CACHE_DIR) -exec sudo rm -rf {} \;
find $(getconf DARWIN_USER_TEMP_DIR) -exec sudo rm -rf {} \;
```

**Comment by larini** [comment] 2024-12-02 23:06
![Image](https://github.com/user-attachments/assets/4516b123-b137-4cbe-879e-0b25af1e2e42)

**Comment by VisualEhrmanntraut** [comment] 2024-12-02 23:07
@larini Now restart

**Closed** 2024-12-11 11:43 UTC
Labels: Unverifiable
