### ISSUE TITLE
Can't play Apple Music and Apple TV's content

### ISSUE THREAD

**Issue by Duucking** [ChefKissInc/NootRX#22] opened 2023-12-20 15:27 UTC
### macOS Version

Ventura

### What is your CPU's model?

AMD Ryzen 7 5700X

### What is your GPU's model?

AMD Radeon RX6700XT

### Please describe the behaviour in detail.

1. Can't play lossless music in Apple Music.
2. Can't play music video in Apple Music, only display black screen.
3. Can't play film in Apple TV, only display black screen.

### What should've happened instead?

Apple Music and Apple TV can work normal.

### If applicable, attach the .gpuRestart, .panic, etc file related to this issue.

kext list:
![截屏2023-12-20 23 26 07](https://github.com/ChefKissInc/NootRX/assets/68683037/3c4d0dda-1c2c-4e41-a602-0ecdb4ffb73f)
boot args:
debug=0x100 keepsyms=1 revcpu=1 alcid=11 agdpmod=pikera -radcodec

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by ExtremeXT** [comment] 2023-12-20 15:28
Duplicate of #4.

**Comment by VisualEhrmanntraut** [comment] 2023-12-20 15:28
Duplicate of #4

**Closed** 2023-12-20 15:28 UTC
Labels: Bug
