### ISSUE TITLE
PP_WorkLoadPolicyMask is not being set correctly. 

### ISSUE THREAD

**Issue by sieskei** [ChefKissInc/NootRX#43] opened 2024-04-03 11:54 UTC
### macOS Version

Sonoma

### What is your CPU's model?

i9-11900KB

### What is your GPU's model?

RX 6650 XT

### Please describe the behaviour in detail.

Hello, first I want to congratulate you on the good work and effort you've put in.

I have two hackintoshes (NUC 11 Extreme) with GPUs 6650XT and 6800XT.
Everything works fine, but PP_WorkLoadPolicyMask on both GPUs has a value of 10 and they have an annoying coil whine.
I noticed that in the plist file a value of 16 is set for the controllers, but it fails to set.

I changed it to 1 (default) and it works. I also tried with 4 (powersaving), and it also works.

I actually solved the problem, I just wanted to share that the value 16 (which I don't know what it means) fails to set.

Regards,
Miro

### What should've happened instead?

Maybe it should be set to 1 by default?

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [x] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by sieskei** [comment] 2024-04-03 12:13
> Hi. 16 is the default value of the macOS drivers; it was copied from them.


I understand.
After you mentioned it, I realized exactly what I was comparing.
In your case (kext), it's in decimal 16, and IORegistryExplorer shows 0x10 (hex), which is exactly 16.
I apologize.

Before closing the ticket, could I ask two more questions?

1. Do I need to set DeviceProperties PP_PhmSoftPowerPlayTable for PP_WorkLoadPolicyMask to work correctly?

2. Are these the allowed values ​​for PP_WorkLoadPolicyMask?
![Screenshot 2024-04-03 at 15 09 01](https://github.com/ChefKissInc/NootRX/assets/58069642/4241591b-4ab8-4aae-8d5c-bdc7e8fc67e8)

**Comment by VisualEhrmanntraut** [comment] 2024-04-03 12:18
@sieskei All the listings of valid values online are incorrect, even WhateverGreen. NootRX does not support setting values with DeviceProperties, modify the kext itself.

**Comment by VisualEhrmanntraut** [comment] 2024-05-22 11:01
Duplicate of #36

**Closed by VisualEhrmanntraut** 2024-05-22 11:01 UTC
Labels: Bug
