### ISSUE TITLE
Lossless audio not working

### ISSUE THREAD

**Issue by PenStar25** [ChefKissInc/NootRX#65] opened 2024-07-01 15:14 UTC
### macOS Version

Ventura

### What is your CPU's model?

ryzen 5600

### What is your GPU's model?

amd 6750gre navi22

### Please describe the behaviour in detail.

Unable to use lossless audio on Applemuic, progress bar cannot be moved.

### What should've happened instead?

Normal use of lossless audio and Dolby

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment] 2024-07-01 15:15
Duplicate of #4

**Closed** 2024-07-03 05:50 UTC
Labels: Duplicate
