### ISSUE TITLE
DRM not supported for Apple TV

### ISSUE THREAD

**Issue by maksimlenskii** [ChefKissInc/NootRX#29] opened 2024-02-17 21:18 UTC
### macOS Version

MacOS Sonoma 14.3.1 (23D60) (Only Navi 21)

### What is your CPU's model?

i9 14900KF

### What is your GPU's model?

Sapphire AMD Radeon RX 6750 GRE

### Please describe the behaviour in detail.

Today I changed the RX5500XT to the RX 6750 GRE. replaced WhateverGreen with NootRX. then reboot, reset nvram - everything loaded perfectly, tests and benchmarks were at a high level. But now I can only watch Apple TV announcements, the content itself is not played

MacOS Sonoma 14.3.1 (23D60)

### What should've happened instead?

Playing movie )

### Bug report submission terms

- [X] I am using the latest version of NootRX.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The bug only happens with NootRX enabled.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by VisualEhrmanntraut** [comment] 2024-02-17 21:19
Duplicate of #4.

**Closed by VisualEhrmanntraut** 2024-02-17 21:19 UTC
Labels: Bug
